adb shell cmd package compile -m speed -f com.android.updater
adb shell cmd package compile -m speed -f com.miui.powerkeeper
adb shell cmd package compile -m speed -f com.miui.miservice
adb shell cmd package compile -m speed -f com.miui.miwallpaper.overlay.customize
adb shell cmd package compile -m speed -f de.szalkowski.activitylauncher
adb shell cmd package compile -m speed -f android.miui.overlay
adb shell cmd package compile -m speed -f org.cromite.cromite
adb shell cmd package compile -m speed -f com.goodix.gftest
adb shell cmd package compile -m speed -f android.miui.home.launcher.res
adb shell cmd package compile -m speed -f com.android.overlay.gmscontactprovider
adb shell cmd package compile -m speed -f com.miui.face
adb shell cmd package compile -m speed -f com.android.providers.contacts
adb shell cmd package compile -m speed -f com.miui.vpnsdkmanager
adb shell cmd package compile -m speed -f com.miui.nextpay
adb shell cmd package compile -m speed -f com.mediaon.apt
adb shell cmd package compile -m speed -f com.android.companiondevicemanager
adb shell cmd package compile -m speed -f com.android.cts.priv.ctsshim
adb shell cmd package compile -m speed -f com.termux
adb shell cmd package compile -m speed -f com.android.providers.downloads
adb shell cmd package compile -m speed -f com.android.bluetoothmidiservice
adb shell cmd package compile -m speed -f com.xiaomi.xmsf
adb shell cmd package compile -m speed -f com.google.android.printservice.recommendation
adb shell cmd package compile -m speed -f com.miui.voiceassist
adb shell cmd package compile -m speed -f com.ms.office365admin
adb shell cmd package compile -m speed -f com.mixplorer.addon.pdf
adb shell cmd package compile -m speed -f com.android.keychain
adb shell cmd package compile -m speed -f com.android.shell
adb shell cmd package compile -m speed -f com.miui.micloudsync
adb shell cmd package compile -m speed -f com.miui.rom
adb shell cmd package compile -m speed -f com.miui.core.internal.services
adb shell cmd package compile -m speed -f com.miui.touchassistant
adb shell cmd package compile -m speed -f com.android.sharedstoragebackup
adb shell cmd package compile -m speed -f com.android.imsserviceentitlement
adb shell cmd package compile -m speed -f com.android.providers.media
adb shell cmd package compile -m speed -f com.android.providers.calendar
adb shell cmd package compile -m speed -f com.android.incallui
adb shell cmd package compile -m speed -f com.android.providers.blockednumber
adb shell cmd package compile -m speed -f com.google.android.documentsui
adb shell cmd package compile -m speed -f com.xiaomi.joyose
adb shell cmd package compile -m speed -f com.android.networkstack.tethering.inprocess
adb shell cmd package compile -m speed -f com.android.statementservice
adb shell cmd package compile -m speed -f com.github.metacubex.clash.meta
adb shell cmd package compile -m speed -f com.mediatek.lbs.em2.ui
adb shell cmd package compile -m speed -f com.miui.audiomonitor
adb shell cmd package compile -m speed -f com.android.proxyhandler
adb shell cmd package compile -m speed -f com.android.calendar
adb shell cmd package compile -m speed -f com.android.emergency
adb shell cmd package compile -m speed -f com.google.android.gms.location.history
adb shell cmd package compile -m speed -f com.android.systemui.deviceconfig.config.overlay
adb shell cmd package compile -m speed -f com.miui.aod
adb shell cmd package compile -m speed -f com.google.android.overlay.gmsconfig
adb shell cmd package compile -m speed -f com.vbook.app
adb shell cmd package compile -m speed -f com.google.android.gm
adb shell cmd package compile -m speed -f com.android.carrierdefaultapp
adb shell cmd package compile -m speed -f com.mediatek.voicecommand
adb shell cmd package compile -m speed -f com.android.backupconfirm
adb shell cmd package compile -m speed -f com.kiwibrowser.browser
adb shell cmd package compile -m speed -f com.miui.uireporter
adb shell cmd package compile -m speed -f com.android.server.telecom.overlay.miui
adb shell cmd package compile -m speed -f com.truedevelopersstudio.automatictap.autoclicker
adb shell cmd package compile -m speed -f com.android.mtp
adb shell cmd package compile -m speed -f com.miui.virtualsim
adb shell cmd package compile -m speed -f com.miui.screenrecorder
adb shell cmd package compile -m speed -f com.miui.translation.kingsoft
adb shell cmd package compile -m speed -f com.android.theme.font.notoserifsource
adb shell cmd package compile -m speed -f com.mobiletools.systemhelper
adb shell cmd package compile -m speed -f com.spotify.music
adb shell cmd package compile -m speed -f com.rhmsoft.edit
adb shell cmd package compile -m speed -f com.android.browser
adb shell cmd package compile -m speed -f com.twofasapp
adb shell cmd package compile -m speed -f com.miui.guardprovider
adb shell cmd package compile -m speed -f com.microsoft.office.officehubrow
adb shell cmd package compile -m speed -f org.ppsspp.ppssppgold
adb shell cmd package compile -m speed -f com.miui.cloudbackup
adb shell cmd package compile -m speed -f com.android.wallpapercropper
adb shell cmd package compile -m speed -f com.miui.contentcatcher
adb shell cmd package compile -m speed -f com.android.internal.systemui.navbar.gestural
adb shell cmd package compile -m speed -f com.android.soundrecorder
adb shell cmd package compile -m speed -f com.miui.systemui.overlay.devices.android
adb shell cmd package compile -m speed -f com.android.settings.intelligence
adb shell cmd package compile -m speed -f tw.nekomimi.nekogram
adb shell cmd package compile -m speed -f com.xiaomi.macro
adb shell cmd package compile -m speed -f com.lbe.security.miui
adb shell cmd package compile -m speed -f com.android.overlay.gmssettings
adb shell cmd package compile -m speed -f net.nguyenthuc.vietnameselunarcalendar
adb shell cmd package compile -m speed -f com.xiaomi.vipaccount
adb shell cmd package compile -m speed -f com.google.android.webview
adb shell cmd package compile -m speed -f com.ixolit.ipvanish
adb shell cmd package compile -m speed -f com.miui.securityadd
adb shell cmd package compile -m speed -f com.android.overlay.cngmstelecomm
adb shell cmd package compile -m speed -f com.android.internal.systemui.navbar.threebutton
adb shell cmd package compile -m speed -f com.miui.systemAdSolution
adb shell cmd package compile -m speed -f com.mediatek.telephony
adb shell cmd package compile -m speed -f com.miui.gallery
adb shell cmd package compile -m speed -f com.mediatek.mdmconfig
adb shell cmd package compile -m speed -f com.android.se
adb shell cmd package compile -m speed -f com.miui.contentextension
adb shell cmd package compile -m speed -f com.newin.nplayer.pro
adb shell cmd package compile -m speed -f com.android.stk
adb shell cmd package compile -m speed -f com.android.overlay.systemui
adb shell cmd package compile -m speed -f com.miui.calculator
adb shell cmd package compile -m speed -f com.android.bips
adb shell cmd package compile -m speed -f com.xiaomi.bluetooth
adb shell cmd package compile -m speed -f com.mediatek.systemuiresoverlay
adb shell cmd package compile -m speed -f com.miui.maintenancemode
adb shell cmd package compile -m speed -f com.android.overlay.gmstelephony
adb shell cmd package compile -m speed -f com.xiaomi.finddevice
adb shell cmd package compile -m speed -f com.miui.notification
adb shell cmd package compile -m speed -f com.android.remoteprovisioner
adb shell cmd package compile -m speed -f com.android.incallui.overlay
adb shell cmd package compile -m speed -f com.xiaomi.location.fused
adb shell cmd package compile -m speed -f com.vttm.vietteldiscovery
adb shell cmd package compile -m speed -f com.mservice.momotransfer
adb shell cmd package compile -m speed -f com.google.android.inputmethod.latin
adb shell cmd package compile -m speed -f miui.systemui.plugin
adb shell cmd package compile -m speed -f com.miui.bugreport
adb shell cmd package compile -m speed -f com.miui.yellowpage
adb shell cmd package compile -m speed -f com.xiaomi.cameratools
adb shell cmd package compile -m speed -f com.miui.catcherpatch
adb shell cmd package compile -m speed -f com.android.networkstack.tethering.overlay
adb shell cmd package compile -m speed -f com.android.providers.downloads.ui
adb shell cmd package compile -m speed -f com.android.ons
adb shell cmd package compile -m speed -f com.google.android.networkstack.tethering.overlay
adb shell cmd package compile -m speed -f com.xiaomi.ugd
adb shell cmd package compile -m speed -f com.miui.mediaeditor
adb shell cmd package compile -m speed -f com.android.wifi.system.mainline.resources.overlay
adb shell cmd package compile -m speed -f com.miui.system
adb shell cmd package compile -m speed -f com.android.wifi.resources
adb shell cmd package compile -m speed -f com.miui.smarttravel
adb shell cmd package compile -m speed -f com.miui.newmidrive
adb shell cmd package compile -m speed -f com.xiaomi.otrpbroker
adb shell cmd package compile -m speed -f com.miui.securitycenter
adb shell cmd package compile -m speed -f com.android.fileexplorer
adb shell cmd package compile -m speed -f com.android.simappdialog
adb shell cmd package compile -m speed -f com.android.wallpaper.livepicker
adb shell cmd package compile -m speed -f com.fido.asm
adb shell cmd package compile -m speed -f com.android.sdksandbox
adb shell cmd package compile -m speed -f com.miui.audioeffect
adb shell cmd package compile -m speed -f com.android.internal.display.cutout.emulation.waterfall
adb shell cmd package compile -m speed -f org.pocketworkstation.pckeyboard
adb shell cmd package compile -m speed -f com.miui.qr
adb shell cmd package compile -m speed -f com.instagram.android
adb shell cmd package compile -m speed -f com.android.systemui.gesture.line.overlay
adb shell cmd package compile -m speed -f org.mozilla.fennec_fdroid
adb shell cmd package compile -m speed -f com.android.traceur
adb shell cmd package compile -m speed -f org.koitharu.kotatsu
adb shell cmd package compile -m speed -f cn.wps.moffice_eng.xiaomi.lite
adb shell cmd package compile -m speed -f com.android.location.fused
adb shell cmd package compile -m speed -f studio.scillarium.ottnavigator
adb shell cmd package compile -m speed -f com.android.cellbroadcastreceiver
adb shell cmd package compile -m speed -f com.xiaomi.migameservice
adb shell cmd package compile -m speed -f com.miui.voicetrigger
adb shell cmd package compile -m speed -f app.rvx.android.youtube
adb shell cmd package compile -m speed -f com.google.android.googlequicksearchbox
adb shell cmd package compile -m speed -f com.termux.api
adb shell cmd package compile -m speed -f com.android.ondevicepersonalization.services
adb shell cmd package compile -m speed -f com.beta.betacineplex
adb shell cmd package compile -m speed -f com.miui.home
adb shell cmd package compile -m speed -f com.google.android.ext.services
adb shell cmd package compile -m speed -f com.google.android.configupdater
adb shell cmd package compile -m speed -f com.miui.wmsvc
adb shell cmd package compile -m speed -f com.xiaomi.gamecenter.sdk.service
adb shell cmd package compile -m speed -f org.ifaa.aidl.manager
adb shell cmd package compile -m speed -f com.android.mms
adb shell cmd package compile -m speed -f com.android.wallpaperpicker
adb shell cmd package compile -m speed -f advanced.scientific.calculator.calc991.plus
adb shell cmd package compile -m speed -f homeworkoutapp.homeworkout.fitness.workout.loseweight
adb shell cmd package compile -m speed -f com.xiaomi.aiasst.vision
adb shell cmd package compile -m speed -f com.mediatek.location.lppe.main
adb shell cmd package compile -m speed -f com.android.internal.display.cutout.emulation.corner
adb shell cmd package compile -m speed -f com.google.android.gms
adb shell cmd package compile -m speed -f com.android.quicksearchbox
adb shell cmd package compile -m speed -f com.xiaomi.mtb
adb shell cmd package compile -m speed -f com.wapi.wapicertmanager
adb shell cmd package compile -m speed -f com.android.packageinstaller
adb shell cmd package compile -m speed -f com.android.systemui.overlay.miui
adb shell cmd package compile -m speed -f com.milink.service
adb shell cmd package compile -m speed -f com.android.thememanager
adb shell cmd package compile -m speed -f com.android.inputsettings.overlay.miui
adb shell cmd package compile -m speed -f com.miui.huanji
adb shell cmd package compile -m speed -f com.android.printspooler
adb shell cmd package compile -m speed -f me.zhanghai.android.files
adb shell cmd package compile -m speed -f com.miui.systemui.devices.overlay
adb shell cmd package compile -m speed -f com.miui.newhome
adb shell cmd package compile -m speed -f com.miui.misound
adb shell cmd package compile -m speed -f app.revanced.android.gms
adb shell cmd package compile -m speed -f com.mixplorer.addon.tagger
adb shell cmd package compile -m speed -f com.miui.wallpaper.overlay.customize
adb shell cmd package compile -m speed -f org.mipay.android.manager
adb shell cmd package compile -m speed -f com.tencent.soter.soterserver
adb shell cmd package compile -m speed -f com.google.android.cellbroadcastservice.overlay.miui
adb shell cmd package compile -m speed -f com.android.externalstorage
adb shell cmd package compile -m speed -f com.android.server.telecom
adb shell cmd package compile -m speed -f com.miui.securityinputmethod
adb shell cmd package compile -m speed -f com.android.camera
adb shell cmd package compile -m speed -f com.miui.daemon
adb shell cmd package compile -m speed -f com.iflytek.inputmethod.miui
adb shell cmd package compile -m speed -f com.shazam.android
adb shell cmd package compile -m speed -f com.miui.tsmclient
adb shell cmd package compile -m speed -f com.android.modulemetadata
adb shell cmd package compile -m speed -f com.android.connectivity.resources
adb shell cmd package compile -m speed -f com.shopee.vn
adb shell cmd package compile -m speed -f com.android.calllogbackup
adb shell cmd package compile -m speed -f com.github.standardadb
adb shell cmd package compile -m speed -f com.anydesk.adcontrol.ad1
adb shell cmd package compile -m speed -f com.mixplorer.addon.image
adb shell cmd package compile -m speed -f com.miui.securitycore
adb shell cmd package compile -m speed -f io.nekohasekai.sagernet.plugin.trojan_go
adb shell cmd package compile -m speed -f com.xiaomi.mibrain.speech
adb shell cmd package compile -m speed -f com.xiaomi.trustservice
adb shell cmd package compile -m speed -f com.zing.zalo
adb shell cmd package compile -m speed -f com.android.dreams.basic
adb shell cmd package compile -m speed -f com.miui.video
adb shell cmd package compile -m speed -f com.android.mms.service
adb shell cmd package compile -m speed -f com.miui.mediaviewer
adb shell cmd package compile -m speed -f com.mfashiongallery.emag
adb shell cmd package compile -m speed -f com.miui.carlink
adb shell cmd package compile -m speed -f com.android.networkstack.overlay
adb shell cmd package compile -m speed -f moe.nb4a
adb shell cmd package compile -m speed -f com.xiaomi.bluetooth.rro.device.config.overlay
adb shell cmd package compile -m speed -f com.mediatek.smartratswitch.service
adb shell cmd package compile -m speed -f com.mediatek.ygps
adb shell cmd package compile -m speed -f com.xiaomi.micloud.sdk
adb shell cmd package compile -m speed -f com.xiaomi.metoknlp
adb shell cmd package compile -m speed -f ru.zdevs.zarchiver
adb shell cmd package compile -m speed -f com.android.wifi.resources.xiaomi
adb shell cmd package compile -m speed -f com.miuix.editor
adb shell cmd package compile -m speed -f com.xiaomi.scanner
adb shell cmd package compile -m speed -f com.android.inputdevices
adb shell cmd package compile -m speed -f com.x8bit.bitwarden
adb shell cmd package compile -m speed -f com.miui.weather2
adb shell cmd package compile -m speed -f com.mediatek.FrameworkResOverlayExt
adb shell cmd package compile -m speed -f com.xiaomi.gnss.polaris
adb shell cmd package compile -m speed -f com.google.android.onetimeinitializer
adb shell cmd package compile -m speed -f com.mediatek.callrecorder
adb shell cmd package compile -m speed -f com.android.carrierconfig.overlay.miui
adb shell cmd package compile -m speed -f com.android.apps.tag
adb shell cmd package compile -m speed -f com.mediatek.SettingsProviderResOverlay
adb shell cmd package compile -m speed -f com.miui.analytics
adb shell cmd package compile -m speed -f com.xiaomi.smarthome
adb shell cmd package compile -m speed -f com.google.android.keep
adb shell cmd package compile -m speed -f com.miui.settings.rro.device.hide.statusbar.overlay
adb shell cmd package compile -m speed -f com.xiaomi.account
adb shell cmd package compile -m speed -f app.hiddify.com
adb shell cmd package compile -m speed -f com.mediatek
adb shell cmd package compile -m speed -f com.miui.thirdappassistant
adb shell cmd package compile -m speed -f com.android.safetycenter.resources
adb shell cmd package compile -m speed -f com.android.managedprovisioning
adb shell cmd package compile -m speed -f com.mediatek.omacp
adb shell cmd package compile -m speed -f com.miui.mishare.connectivity
adb shell cmd package compile -m speed -f com.mediatek.mdmlsample
adb shell cmd package compile -m speed -f com.miui.translationservice
adb shell cmd package compile -m speed -f com.xiaomi.payment
adb shell cmd package compile -m speed -f com.foxdebug.acode
adb shell cmd package compile -m speed -f com.lgeha.nuts
adb shell cmd package compile -m speed -f com.zhiliaoapp.musically
adb shell cmd package compile -m speed -f com.xiaomi.mi_connect_service
adb shell cmd package compile -m speed -f is.xyz.mpv.ytdl
adb shell cmd package compile -m speed -f com.android.nfc
adb shell cmd package compile -m speed -f com.android.cellbroadcastservice
adb shell cmd package compile -m speed -f com.google.android.gsf
adb shell cmd package compile -m speed -f com.android.systemui.navigation.bar.overlay
adb shell cmd package compile -m speed -f com.gorillasoftware.everyproxy
adb shell cmd package compile -m speed -f com.android.settings.resource.overlay
adb shell cmd package compile -m speed -f com.android.internal.display.cutout.emulation.double
adb shell cmd package compile -m speed -f com.mediatek.frameworkresoverlay
adb shell cmd package compile -m speed -f com.xiaomi.simactivate.service
adb shell cmd package compile -m speed -f com.miui.personalassistant
adb shell cmd package compile -m speed -f com.vnpay.vpbankonline
adb shell cmd package compile -m speed -f com.miui.greenguard
adb shell cmd package compile -m speed -f com.mediatek.op09clib.telecom
adb shell cmd package compile -m speed -f com.android.managedprovisioning.overlay
adb shell cmd package compile -m speed -f com.android.systemui
adb shell cmd package compile -m speed -f com.xiaomi.security.onetrack
adb shell cmd package compile -m speed -f com.microsoft.skydrive
adb shell cmd package compile -m speed -f com.android.wifi.system.resources.overlay
adb shell cmd package compile -m speed -f com.baidu.input_mi
adb shell cmd package compile -m speed -f com.google.android.apps.translate
adb shell cmd package compile -m speed -f com.xiaomi.aicr
adb shell cmd package compile -m speed -f com.android.settings.overlay.miui
adb shell cmd package compile -m speed -f com.miui.player
adb shell cmd package compile -m speed -f com.hdobox
adb shell cmd package compile -m speed -f com.looker.droidify
adb shell cmd package compile -m speed -f com.monster.monstertv
adb shell cmd package compile -m speed -f com.miui.phrase
adb shell cmd package compile -m speed -f com.mediatek.op09clib.phone.plugin
adb shell cmd package compile -m speed -f com.miui.extraphoto
adb shell cmd package compile -m speed -f com.bsp.catchlog
adb shell cmd package compile -m speed -f com.android.deskclock
adb shell cmd package compile -m speed -f com.android.wallpaperbackup
adb shell cmd package compile -m speed -f in.sunilpaulmathew.ashell
adb shell cmd package compile -m speed -f com.google.android.networkstack.overlay
adb shell cmd package compile -m speed -f com.miui.core
adb shell cmd package compile -m speed -f com.miui.settings.rro.device.type.overlay
adb shell cmd package compile -m speed -f com.android.localtransport
adb shell cmd package compile -m speed -f idm.internet.download.manager.plus
adb shell cmd package compile -m speed -f android
adb shell cmd package compile -m speed -f com.duokan.phone.remotecontroller
adb shell cmd package compile -m speed -f com.miui.compass
adb shell cmd package compile -m speed -f com.mediatek.voiceunlock
adb shell cmd package compile -m speed -f com.mediatek.cellbroadcastuiresoverlay
adb shell cmd package compile -m speed -f com.termux.styling
adb shell cmd package compile -m speed -f com.android.permissioncontroller
adb shell cmd package compile -m speed -f com.logame.eliminateintruder3d
adb shell cmd package compile -m speed -f com.miui.face.overlay.miui
adb shell cmd package compile -m speed -f dev.imranr.obtainium.fdroid
adb shell cmd package compile -m speed -f com.android.pacprocessor
adb shell cmd package compile -m speed -f com.miui.accessibility
adb shell cmd package compile -m speed -f com.android.wifi.resources.overlay
adb shell cmd package compile -m speed -f com.android.providers.media.module
adb shell cmd package compile -m speed -f com.miui.freeform
adb shell cmd package compile -m speed -f com.xiaomi.digitalkey
adb shell cmd package compile -m speed -f com.android.internal.display.cutout.emulation.hole
adb shell cmd package compile -m speed -f com.android.settings
adb shell cmd package compile -m speed -f com.mediatek.engineermode
adb shell cmd package compile -m speed -f com.android.internal.systemui.navbar.gestural_narrow_back
adb shell cmd package compile -m speed -f com.mediatek.miravision.ui
adb shell cmd package compile -m speed -f com.android.internal.display.cutout.emulation.tall
adb shell cmd package compile -m speed -f com.android.cameraextensions
adb shell cmd package compile -m speed -f com.android.networkstack.inprocess.overlay
adb shell cmd package compile -m speed -f com.miui.notes
adb shell cmd package compile -m speed -f com.android.carrierconfig
adb shell cmd package compile -m speed -f com.android.internal.systemui.navbar.gestural_wide_back
adb shell cmd package compile -m speed -f com.lazada.android
adb shell cmd package compile -m speed -f com.google.android.ext.shared
adb shell cmd package compile -m speed -f com.google.android.apps.bard
adb shell cmd package compile -m speed -f com.miui.packageinstaller
adb shell cmd package compile -m speed -f com.mixplorer
adb shell cmd package compile -m speed -f com.android.networkstack.inprocess
adb shell cmd package compile -m speed -f com.xiaomi.xmsfkeeper
adb shell cmd package compile -m speed -f com.google.android.apps.maps
adb shell cmd package compile -m speed -f com.grabtaxi.passenger
adb shell cmd package compile -m speed -f com.debug.loggerui
adb shell cmd package compile -m speed -f com.android.adservices.api
adb shell cmd package compile -m speed -f com.modemdebug
adb shell cmd package compile -m speed -f com.google.android.overlay.modules.ext.services.cn
adb shell cmd package compile -m speed -f com.google.android.marvin.talkback
adb shell cmd package compile -m speed -f mobi.mangatoon.comics.aphone
adb shell cmd package compile -m speed -f com.xiaomi.aiasst.service
adb shell cmd package compile -m speed -f com.xiaomi.ab
adb shell cmd package compile -m speed -f com.miui.fmservice
adb shell cmd package compile -m speed -f com.miui.miwallpaper
adb shell cmd package compile -m speed -f com.yscoco.yssound
adb shell cmd package compile -m speed -f com.miui.cit
adb shell cmd package compile -m speed -f com.miui.vsimcore
adb shell cmd package compile -m speed -f xyz.be.customer
adb shell cmd package compile -m speed -f com.android.certinstaller
adb shell cmd package compile -m speed -f com.mixplorer.addon.codecs
adb shell cmd package compile -m speed -f com.miui.hybrid
adb shell cmd package compile -m speed -f com.google.android.tts1
adb shell cmd package compile -m speed -f bin.mt.termex
adb shell cmd package compile -m speed -f com.android.wifi.dialog
adb shell cmd package compile -m speed -f com.miui.cleanmaster
adb shell cmd package compile -m speed -f com.android.captiveportallogin
adb shell cmd package compile -m speed -f com.xiaomi.market
adb shell cmd package compile -m speed -f com.miui.systemui.carriers.overlay
adb shell cmd package compile -m speed -f com.mixplorer.addon.archive
adb shell cmd package compile -m speed -f com.miui.backup
adb shell cmd package compile -m speed -f com.mediatek.op01.telecom
adb shell cmd package compile -m speed -f com.android.providers.telephony
adb shell cmd package compile -m speed -f com.miui.settings.rro.device.config.overlay
adb shell cmd package compile -m speed -f com.xiaomi.xaee
adb shell cmd package compile -m speed -f com.xiaomi.barrage
adb shell cmd package compile -m speed -f com.android.providers.settings
adb shell cmd package compile -m speed -f com.android.overlay.gmssettingprovider
adb shell cmd package compile -m speed -f com.android.phone
adb shell cmd package compile -m speed -f com.android.internal.systemui.navbar.gestural_extra_wide_back
adb shell cmd package compile -m speed -f com.android.stk.overlay.miui
adb shell cmd package compile -m speed -f android.aosp.overlay
adb shell cmd package compile -m speed -f com.android.bluetooth.overlay
adb shell cmd package compile -m speed -f com.android.contacts
adb shell cmd package compile -m speed -f com.instagram.barcelona
adb shell cmd package compile -m speed -f com.xiaomi.mirror
adb shell cmd package compile -m speed -f com.facebook.orca
adb shell cmd package compile -m speed -f com.android.overlay.gmstelecomm
adb shell cmd package compile -m speed -f io.nekohasekai.sfa
adb shell cmd package compile -m speed -f en.hyperosdownloader
adb shell cmd package compile -m speed -f com.android.vpndialogs
adb shell cmd package compile -m speed -f com.android.uwb.resources
adb shell cmd package compile -m speed -f com.miui.screenshot
adb shell cmd package compile -m speed -f com.google.android.cellbroadcastreceiver.overlay.miui
adb shell cmd package compile -m speed -f com.mediatek.batterywarning
adb shell cmd package compile -m speed -f com.android.htmlviewer
adb shell cmd package compile -m speed -f com.android.vending
adb shell cmd package compile -m speed -f com.mixplorer.addon.autotag
adb shell cmd package compile -m speed -f com.mediatek.op01.phone.plugin
adb shell cmd package compile -m speed -f com.miui.system.overlay
adb shell cmd package compile -m speed -f com.miui.miinput
adb shell cmd package compile -m speed -f com.trustonic.teeservice
adb shell cmd package compile -m speed -f com.android.providers.settings.overlay
adb shell cmd package compile -m speed -f com.wondershare.mobilego.connector
adb shell cmd package compile -m speed -f com.mediatek.capctrl.service
adb shell cmd package compile -m speed -f com.android.networkstack.tethering.inprocess.overlay
adb shell cmd package compile -m speed -f com.mediatek.ims
adb shell cmd package compile -m speed -f com.android.providers.userdictionary
adb shell cmd package compile -m speed -f com.mi.health
adb shell cmd package compile -m speed -f com.android.cts.ctsshim
adb shell cmd package compile -m speed -f com.android.bluetooth
adb shell cmd package compile -m speed -f com.phim4k
adb shell cmd package compile -m speed -f com.mbmobile
adb shell cmd package compile -m speed -f com.discord
adb shell cmd package compile -m speed -f com.android.storagemanager
adb shell cmd package compile -m speed -f com.fingerprints.sensortesttool
adb shell cmd package compile -m speed -f com.miui.cloudservice
adb shell cmd package compile -m speed -f com.mediatek.location.mtkgeofence
adb shell cmd package compile -m speed -f com.miui.voiceassistoverlay
adb shell cmd package compile -m speed -f com.bplus.vtpay
adb shell cmd package compile -m speed -f com.android.phone.overlay.miui
adb shell cmd package compile -m speed -f com.miui.otaprovision
adb shell cmd package compile -m speed -f com.xiaomi.misettings
adb shell cmd package compile -m speed -f com.amazon.appmanager
adb shell cmd package compile -m speed -f com.android.provision
adb shell cmd package compile -m speed -f com.mediatek.gbaservice
adb shell cmd package compile -m speed -f com.facebook.katana
adb shell cmd package compile -m speed -f com.mipay.wallet
adb shell cmd package compile -m speed -f com.android.dynsystem
adb shell cmd package compile -m speed -f moe.shizuku.privileged.api
adb shell cmd package compile -m speed -f com.anydesk.anydeskandroid
adb shell cmd package compile -m speed -f com.cloudflare.onedotonedotonedotone
adb shell cmd package compile -m speed -f com.sohu.inputmethod.sogou.xiaomi
adb shell cmd package compile -m speed -f com.android.hotspot2.osulogin
adb shell cmd package compile -m speed -f com.unionpay.tsmservice.mi
adb shell cmd package compile -m speed -f com.miui.translation.xmcloud
adb shell cmd package compile -m speed -f com.microsoft.rdc.androidx
adb shell cmd package compile -m speed -f com.android.provision.resource.overlay
adb shell cmd package compile -m speed -f com.playdigious.deadcells.mobile